### ISSUE TITLE
Error Emails

### ISSUE THREAD

**Issue by ghost** [DouglasCAyers/sfdc-add-campaign-members-by-report#7]
Hi @DouglasCAyers 

I have attached the two Debug Logs for you to take a look.

39.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
09:36:19.0 (679875)|USER_INFO|[EXTERNAL]|005570000076ZWr|redacted@redacted.com|Pacific Standard Time|GMT-07:00
09:36:19.0 (7195829)|ENTERING_MANAGED_PKG|dca_cmpgn_apps
09:36:19.0 (28649593)|ENTERING_MANAGED_PKG|dca_cmpgn_apps
09:36:19.0 (28835394)|ENTERING_MANAGED_PKG|dca_cmpgn_apps
09:36:19.0 (291971862)|ENTERING_MANAGED_PKG|dca_cmpgn_apps
09:36:19.0 (292105740)|HEAP_ALLOCATE|[66]|Bytes:11
09:36:19.0 (292147253)|HEAP_ALLOCATE|[66]|Bytes:33
09:36:19.0 (292151147)|HEAP_ALLOCATE|[66]|Bytes:30
09:36:19.0 (292154068)|HEAP_ALLOCATE|[66]|Bytes:12
09:36:19.0 (292250382)|SYSTEM_METHOD_ENTRY|[EXTERNAL]|ArrayList.ArrayList()
09:36:19.0 (292255289)|STATEMENT_EXECUTE|[EXTERNAL]
09:36:19.0 (292259745)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292275989)|SYSTEM_METHOD_EXIT|[EXTERNAL]|ArrayList
09:36:19.0 (292283271)|HEAP_ALLOCATE|[214]|Bytes:16
09:36:19.0 (292310323)|CONSTRUCTOR_ENTRY|[214]||<init>(int)
09:36:19.0 (292313757)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292360523)|CONSTRUCTOR_ENTRY|[150]||<init>()
09:36:19.0 (292365534)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292417459)|CONSTRUCTOR_ENTRY|[76]||<init>()
09:36:19.0 (292421667)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292486374)|SYSTEM_METHOD_ENTRY|[EXTERNAL]|Collections.Collections()
09:36:19.0 (292489383)|STATEMENT_EXECUTE|[EXTERNAL]
09:36:19.0 (292492171)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292501944)|HEAP_ALLOCATE|[4279]|Bytes:4
09:36:19.0 (292523254)|CONSTRUCTOR_ENTRY|[4279]||<init>(java.util.Collections.1)
09:36:19.0 (292526402)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292545395)|CONSTRUCTOR_ENTRY|[4308]||<init>()
09:36:19.0 (292547759)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292568494)|CONSTRUCTOR_ENTRY|[4308]||<init>()
09:36:19.0 (292571140)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292576998)|CONSTRUCTOR_ENTRY|[63]||<init>()
09:36:19.0 (292578819)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292616897)|HEAP_ALLOCATE|[4397]|Bytes:8
09:36:19.0 (292631495)|CONSTRUCTOR_ENTRY|[4397]||<init>(java.util.Collections.1)
09:36:19.0 (292634217)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292651013)|CONSTRUCTOR_ENTRY|[4427]||<init>()
09:36:19.0 (292653168)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292672890)|CONSTRUCTOR_ENTRY|[4427]||<init>()
09:36:19.0 (292675196)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292680428)|CONSTRUCTOR_ENTRY|[76]||<init>()
09:36:19.0 (292682239)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292713189)|HEAP_ALLOCATE|[4498]|Bytes:12
09:36:19.0 (292727180)|CONSTRUCTOR_ENTRY|[4498]||<init>(java.util.Collections.1)
09:36:19.0 (292729673)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292755028)|CONSTRUCTOR_ENTRY|[4568]||<init>()
09:36:19.0 (292757615)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292777556)|CONSTRUCTOR_ENTRY|[4568]||<init>()
09:36:19.0 (292779944)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292798651)|SYSTEM_METHOD_EXIT|[EXTERNAL]|Collections
09:36:19.0 (292806655)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292844291)|HEAP_ALLOCATE|[1287]|Bytes:12
09:36:19.0 (292859943)|CONSTRUCTOR_ENTRY|[1287]||<init>(java.util.List)
09:36:19.0 (292862579)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292888413)|CONSTRUCTOR_ENTRY|[1395]||<init>(java.util.List)
09:36:19.0 (292890914)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (292917230)|CONSTRUCTOR_ENTRY|[1302]||<init>(java.util.Collection)
09:36:19.0 (292919843)|ENTERING_MANAGED_PKG|java__util
09:36:19.0 (293006497)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293025555)|HEAP_ALLOCATE|[783]|Bytes:16
09:36:19.0 (293027694)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293037703)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293039534)|HEAP_ALLOCATE|[783]|Bytes:16
09:36:19.0 (293041012)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293044391)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293046256)|HEAP_ALLOCATE|[783]|Bytes:6
09:36:19.0 (293047764)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293050691)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293052556)|HEAP_ALLOCATE|[783]|Bytes:6
09:36:19.0 (293053965)|HEAP_ALLOCATE|[783]|Bytes:19
09:36:19.0 (293057027)|HEAP_ALLOCATE|[783]|Bytes:24
09:36:19.0 (293058773)|HEAP_ALLOCATE|[783]|Bytes:6
09:36:19.0 (293060141)|HEAP_ALLOCATE|[783]|Bytes:24
09:36:19.0 (293062987)|HEAP_ALLOCATE|[783]|Bytes:86
09:36:19.0 (293064699)|HEAP_ALLOCATE|[783]|Bytes:6
09:36:19.0 (293066170)|HEAP_ALLOCATE|[783]|Bytes:86
09:36:19.0 (293069354)|HEAP_ALLOCATE|[783]|Bytes:50
09:36:19.0 (293071105)|HEAP_ALLOCATE|[783]|Bytes:6
09:36:19.0 (293072526)|HEAP_ALLOCATE|[783]|Bytes:50
09:36:19.0 (293075475)|HEAP_ALLOCATE|[783]|Bytes:47
09:36:19.0 (293077629)|HEAP_ALLOCATE|[783]|Bytes:7
09:36:19.0 (293079019)|HEAP_ALLOCATE|[783]|Bytes:47

39.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
09:36:18.0 (115643)|EXECUTION_STARTED
09:36:18.0 (169994)|CODE_UNIT_STARTED|[EXTERNAL]|VisualForce View State
09:36:18.0 (7957635)|CODE_UNIT_FINISHED|VisualForce View State
09:36:18.0 (8884769)|EXECUTION_FINISHED
09:36:18.10 (10205582)|SYSTEM_MODE_ENTER|true
09:36:18.10 (10367039)|HEAP_ALLOCATE|[72]|Bytes:3
09:36:18.10 (10415567)|HEAP_ALLOCATE|[77]|Bytes:152
09:36:18.10 (10432266)|HEAP_ALLOCATE|[342]|Bytes:408
09:36:18.10 (10451560)|HEAP_ALLOCATE|[355]|Bytes:408
09:36:18.10 (10470396)|HEAP_ALLOCATE|[467]|Bytes:48
09:36:18.261 (261170035)|CUMULATIVE_LIMIT_USAGE
09:36:18.261 (261170035)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 0 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

09:36:18.261 (261170035)|CUMULATIVE_LIMIT_USAGE_END

**Comment by douglascayers** [comment]
Thanks @meganmeric  for collecting the debug logs. Unfortunately, since I provided a managed package option, now the info I need in the log files is hidden from us. doh! Let me see if there's another way to troubleshoot this. Thanks

**Comment by douglascayers** [comment]
Hi @meganmeric,

Thanks for your patience. I've released new version, 1.6, of this app. Installation links are available on the project README page. Please upgrade and let me know if you continue to encounter errors. A new tab "Add Campaign Members by Report Logs" is available in the new package that might shed some light on what's happening.

Thanks,

Doug

**Comment by ghost** [comment]
Hi Doug,

Sorry I am just now getting back to you. I upgraded and I am still getting the same error emails ☹

I ran the report logs as well and they are blank?

**Comment by douglascayers** [comment]
Hi Megan, I'll send you a DM to further troubleshoot.

**Comment by douglascayers** [comment]
Hi @meganmeric,

Did you ever get this working for you?

Thanks,

Doug
